name: Pull request checks

on:
  push:
    branches: [ main ]
  pull_request:

env:
  JAVA_VERSION: '21'
  DOTNET_VERSION: '8.0.x'

jobs:
  lint:
    name: Lint Cypress
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0 # Shallow clones disabled for a better relevancy of SC analysis

    - name: lint cypress tests
      run: |
        cd Dfe.PrepareConversions/Dfe.PrepareConversions.CypressTests
        npm ci
        npm run lint

  build:
    name: Build .NET, Test and Analyse
    runs-on: ubuntu-24.04
    services:
      redis:
        image: redis:alpine@sha256:48501c5ad00d5563bc30c075c7bcef41d7d98de3e9a1e6c752068c66f0a8463b
        ports:
        - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0 # Shallow clones disabled for a better relevancy of SC analysis

    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'microsoft'

    - name: Cache SonarCloud packages
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Install SonarCloud scanners
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Install dotnet reportgenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Add nuget package source
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DFE-Digital/index.json"

    - name: Restore dependencies
      run: dotnet restore Dfe.PrepareConversions/Dfe.PrepareConversions.sln

    - name: Build, Test and Analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        ConnectionStrings__RedisCache: "127.0.0.1:6379,ssl=False,abortConnect=False"
      run: |
        dotnet-sonarscanner begin /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /o:dfe-digital /k:DFE-Digital-prepare-conversions /s:${{ github.workspace }}/SonarQube.Analysis.xml  
        dotnet build Dfe.PrepareConversions/Dfe.PrepareConversions.sln --no-restore
        dotnet test Dfe.PrepareConversions/Dfe.PrepareConversions.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" -m:1
        reportgenerator -reports:"./**/coverage.cobertura.xml" -targetdir:./Dfe.PrepareConversions/CoverageReport -reporttypes:SonarQube
        dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
