name: Deploy to environment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Choose an environment to deploy to"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }}

env:
  NODE_VERSION: 18.x
  IMAGE_NAME: a2bint-app

jobs:
  set-env:
    name: Determine environment
    runs-on: ubuntu-24.04
    outputs:
      environment: ${{ steps.var.outputs.environment }}
      release: ${{ steps.var.outputs.release }}
      image-name: ${{ steps.var.outputs.image-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - id: var
        run: |
          INPUT=${{ github.event.inputs.environment }}
          ENVIRONMENT=${INPUT:-"dev"}
          RELEASE=${ENVIRONMENT,,}-`date +%Y-%m-%d`.${{ github.run_number }}
          echo "environment=${ENVIRONMENT,,}" >> $GITHUB_OUTPUT
          echo "release=${RELEASE}" >> $GITHUB_OUTPUT
          echo "image-name=${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT

  validate-packages:
    runs-on: windows-latest
    name: Package Validation
    permissions:
      contents: read
    needs: [ set-env ]
    steps:
      - name: Validate Packages
        uses: DFE-Digital/rsd-github-actions/.github/actions/validate-packages@9a7a6a7c9aa5914f76a1f34aee8dd2dcc00702bc # v1.1.2
        with:
          environment: ${{ needs.set-env.outputs.environment }}

  deploy:
    name: Build, Import, Deploy
    needs: [ set-env, validate-packages ]
    runs-on: ubuntu-24.04
    environment: ${{ needs.set-env.outputs.environment }}
    permissions:
      packages: write
      id-token: write
      attestations: write
    steps:
      - uses: DFE-Digital/deploy-azure-container-apps-action/.github/actions/build@v5.2.0
        with:
          build-file-name: ./Dockerfile
          build-args: CI=true
          image-name: ${{ needs.set-env.outputs.image-name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DFE-Digital/deploy-azure-container-apps-action/.github/actions/import@v5.2.0
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-acr-client-id: ${{ secrets.ACR_CLIENT_ID }}
          azure-acr-name: ${{ secrets.ACR_NAME }}
          image-name: ${{ needs.set-env.outputs.image-name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID || '' }}
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION_ID || '' }}
          AZURE_ACR_CLIENT_ID: ${{ secrets.ACR_CLIENT_ID || '' }}

      - uses: DFE-Digital/deploy-azure-container-apps-action/.github/actions/deploy@v5.2.0
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-aca-client-id: ${{ secrets.ACA_CLIENT_ID }}
          azure-aca-name: ${{ secrets.ACA_CONTAINERAPP_NAME }}
          azure-aca-resource-group: ${{ secrets.ACA_RESOURCE_GROUP }}
          azure-acr-name: ${{ secrets.ACR_NAME }}
          annotate-release: 'yes'
          image-name: ${{ needs.set-env.outputs.image-name }}
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID || '' }}
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION_ID || '' }}
          AZURE_ACA_CLIENT_ID: ${{ secrets.ACA_CLIENT_ID || '' }}

  create-tag:
    name: Tag and release
    needs: [ set-env, deploy ]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.ref }}

      - name: Create tag
        run: |
          git tag ${{ needs.set-env.outputs.release }}
          git push origin ${{ needs.set-env.outputs.release }}

      - name: Create release
        uses: "actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea" # v7
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: "${{ needs.set-env.outputs.release }}",
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: "${{ needs.set-env.outputs.release }}",
              });
            } catch (error) {
              core.setFailed(error.message);
            }

  cypress-tests:
    name: Run Cypress Tests
    if: needs.set-env.outputs.environment == 'staging' || needs.set-env.outputs.environment == 'dev'
    needs: [ deploy, set-env ]
    uses: ./.github/workflows/cypress.yml
    with:
      environment: ${{ needs.set-env.outputs.environment }}
    secrets: inherit
