name: Cypress tests

on:
  workflow_run:
    workflows: ["Deploy to environment (CIP)"]
    branches: [ main ]
    types:
      - completed

env:
  NODE_VERSION: 18.x

jobs:
  cypress-tests:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.inputs.environment != 'Production'
    environment: ${{ github.event.workflow_run.inputs.environment }}
    runs-on: ubuntu-22.04
    defaults:
      run:
         working-directory: Dfe.PrepareConversions/Dfe.PrepareConversions.CypressTests
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Npm install
        run: npm install

      - name: Run cypress
        run: npm run cy:run -- --env url='${{ secrets.ENDPOINT }}',authorizationHeader='${{ secrets.CYPRESS_TEST_SECRET }}'
        env:
          db: ${{ secrets.DB_CONNECTION_STRING }}

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
         name: screenshots-${{ github.event.workflow_run.inputs.environment }}
         path: Dfe.PrepareConversions/Dfe.PrepareConversions.CypressTests/cypress/screenshots
